services:
  api:
    build:
      context: ..          # Apunta a la raíz del repositorio
      dockerfile: dockerfile
    image: marcocantugea/incident-remediation-api:local # Nombre local para tu imagen
    container_name: incident_remediation_api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s